# Generated by Django 4.2.1 on 2023-06-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Image_URL',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='URL',
            field=models.CharField(max_length=10000),
        ),
    ]
